name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['24.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'npm'

      - name: Install deps (with cache)
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run a type-check to make sure no build-time errors
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
