name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch
        required: false
        default: main

jobs:
  release:
    name: Build, lint, test, release the library.
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: "npm"

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install deps (with cache)
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Semantic Release
        run: npx semantic-release@beta --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
